### ISSUE TITLE
Avoid using ID-based css selectors

### ISSUE THREAD

**Issue by alextanasie** [AlexandruAdrian/twitter-clone#1]
Use only classes or element selectors instead.
https://github.com/AlexandruAdrian/twitter-clone/blob/dab83fe8b6a61b0ba36055a91724254c3a028eb7/index.html#L28

**Comment by AlexandruAdrian** [comment]
Fixed by replacing ids with classes --  https://github.com/AlexandruAdrian/twitter-clone/commit/c11c25210d1c2efa6a282c752ffb99cd49615247
