### ISSUE TITLE
No need for footer in retweets

### ISSUE THREAD

**Issue by alextanasie** [AlexandruAdrian/twitter-clone#3]
_No biggie_
![Screenshot 2020-03-04 at 17 52 16](https://user-images.githubusercontent.com/18068016/75897222-e7513c00-5e40-11ea-91ad-b7c03bb56d96.png)

https://github.com/AlexandruAdrian/twitter-clone/blob/dab83fe8b6a61b0ba36055a91724254c3a028eb7/index.html#L234

**Comment by AlexandruAdrian** [comment]
Removed footer from retweets 28063865ba9ae2b3fd1c68501cb3fe2df043b05d. Thank you for pointing out my mistakes, if you have any more suggestions I will gladly accept and try to follow them.
